### ISSUE TITLE
1. Init a Project

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/hchocobar-basic-project#2]
# Task list

- [x] Init DB and first migrate
- [x] Open new terminal and open port 3000 with npm run start (front terminal)
- [x] Open new terminal and open port 3001 witn pipenv run start (back terminal)
- [x] Change port 3001 to public
- [x] Setup variable BACKEND_URL in .env

**Comment by hchocobar** [comment]
# Setup variable BACKEND_URL

![image](https://github.com/4GeeksAcademy/hchocobar-little-back-project/assets/45291267/6147a746-e356-487a-94e6-0b750712fe24)
