### ISSUE TITLE
4. Build a CRUD through endpoints

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/hchocobar-basic-project#7]
# CRUD

## Task list

- [ ] Get all users
- [ ] Create new user
- [ ] Get an user for given id
- [ ] Update an user for given id
- [ ] Delete an user for given id

## Documentation

[SQLAlchemy - Query the Data](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/quickstart/#query-the-data)

[SQLAlchemy - Modifying and Querying Data](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/queries/)
